CUES_DIR = "cues"
CUES_FILE = "cues.txt"
BINARY_PATH = "bin"
WIDTH = 1920
HEIGHT = 1080
FONT = "arial.ttf"
FONT_SIZE = 72  # px
FONT_POSITION = 2  # percent from top
LINE_SPACING = 1.15
OUTPUT_DIR = "cues/temp"
