CUES_DIR = "cues"
OUTPUT_DIR = f"{CUES_DIR}/temp"
CUES_FILE = f"{CUES_DIR}/cues.txt"
METADATA_FILE = f"{OUTPUT_DIR}/metadata.json"
BINARY_DIR = "bin"
WIDTH = 1920 # text cue image width
HEIGHT = 1080 # text cue image height
FONT = "tahoma.ttf"
FONT_SIZE = 72  # px
FONT_POSITION = 2  # percent from top
LINE_SPACING = 1.15
CUE_LIST_MIDDLE = 50 # percent from top where current cue should be
